battles = [ENEMY_INDEX.SKELLY, ENEMY_INDEX.TRIZER, ENEMY_INDEX.CANDLE_AND_MOSS, ENEMY_INDEX.NOOB_TIME_TRIO, ENEMY_INDEX.DFW, ENEMY_INDEX.KACPII, ENEMY_INDEX.NATO, ENEMY_INDEX.HUGOSIMPSON, ENEMY_INDEX.CHEESY, ENEMY_INDEX.PLAYERUT, ENEMY_INDEX.SHAUN_AND_MINUS, ENEMY_INDEX.MAKER, ENEMY_INDEX.ENZO];
titles = [ENEMY_TITLE_SKELLY, ENEMY_TITLE_TRIZER, ENEMY_TITLE_CANDLE_AND_MOSS, ENEMY_TITLE_NOOB_TIME_TRIO, ENEMY_TITLE_DFW, ENEMY_TITLE_KACPII, ENEMY_TITLE_NATO, ENEMY_TITLE_HUGOSIMPSON, ENEMY_TITLE_CHEESY, ENEMY_TITLE_PLAYERUT, ENEMY_TITLE_SHAUN_AND_MINUS, ENEMY_TITLE_MAKER, ENEMY_TITLE_ENZO];
selected_battle = (array_length(battles) - 1) * 9999;
selection_display = selected_battle;
hold_time = 0;